### ISSUE TITLE
Remove hardcoded credentials

### ISSUE THREAD

**Issue by NavitaireSecurity** [hrushikesh-udchalo/helper-express#1]
It looks like you have hardcoded test API credentials in your application.  This is a well-known security weakness.  Please see OWASP guidance for further info: https://owasp.org/www-community/vulnerabilities/Password_Management_Hardcoded_Password

Navitaire has notified our customer of this error and deactivated the account mentioned herein.

**Comment by hrushikesh-udchalo** [comment]
Removed, Thanks !!
